spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiao?serverTimezone=Asia/Shanghai
    username: root
    password: admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    static-path-pattern: /static/**


logging:
  level:
    com.example.bdatabaserole.mapper: debug  # 打印sql语句


#  security:
#    user:
#      name: test   # 用户名
#      password: 123456  # 密码
#      roles: # 角色
#        - user
#        - admin

#开发环境